services:

  netschach-bot:
    image: netschach-bot
    ports:
      - "8080:8080"
    depends_on:
      - echo

  echo:
    build:
      context: ../..
      dockerfile: docker/echo/Dockerfile
    ports:
      - "8000:8000"
